(ns example.utils.strings)

(def texts
  {:app-title "RK360®NAVI"
   :section-title "MUST SAVE INFORMATION"
   :paragraph "TO SAFEGUARD CONTENTS OF YOUR RK360® CLOUD HEALTH RECORD, WRITE DOWN INFORMATION LISTED BELOW ON TWO PAPER NOTES. KEEP ONE NOTE WITH YOU WHEREVER YOU GO AND STORE THE SECOND NOTE WITH YOUR IMPORTANT PAPERS."
   :username-label "Your unique Username is:"
   :info-text-username "You will need this Username for rapid no-cost App Sign In when your email address and mobile phone number changes."
   :recovery-label "Your unique Recovery Phrase is:"
   :recovery-phrase "health slot another turtle joke girl dance sniff expand mixed tissue congress inch stick silver lock mention walk humor bunker team inner lawsuit two"
   :info-text-recovery "If two-factor authentication fails, you will need your Recovery Phrase for rapid, no-cost unlocking of your RK360® App and for other App management purposes."
   :checkbox-text-1 "Yes. I have written down the five types of information listed below on two paper notes. I will keep one note with me wherever I go and store the second note with my important papers. I further confirm that I have not put this information in an electronic file that a bad actor might locate."
   :checkbox-text-2 "Yes. If I forget my verbal passcode, Username or Recovery Phrase, and therefore cannot employ them, at no cost, to unlock my locked RK360® App, to identify myself to customer support or for other App management purposes, I will pay $150 for processing of a notarized affidavit verifying my identity."
   :agree-button "I AGREE TO ALL THE TERMS ABOVE"
   :username "1. Username (assigned above)"
   :recoverytext "2. Recovery Phrase (assigned above)"
   :verbal-password "3. Verbal Passcode (entered when subscribing)"
   :emailaddress "4. Email Address (entered when subscribing)"
   :mobilenumber "5. Mobile Phone Number (entered when subscribing)"
   :agreebuttontext "I AGREE TO ALL THE TERMS ABOVE"
   :smscode "Enter Sms Code"
   :submitcode "SUBMIT CODE"
   :resendcode "RESEND CODE"
   :backsignin "Back to Sign in Details"
   :codeviatext "Enter the Code sent via SMS text"
   :codevianumber "Enter the Code sent via SMS text to the RK360 Record Administrator’s mobile phone."
   :paramsmissing "Error: Parameters are missing"
   :signupheader "SUBSCRIBE"
   :descriptionsignup "To subscribe to the plan you chose, add details that identify you as the plan's Record Administrator and let you Sign In to the RK360 App."
   :planselection "Click here to choose a different plan."
   :backbutton "BACK"
   :signintitle "Sign In"
   :signmeup "Sign Me Up"
   :forgotpass "Forgot password?"
   :lockedout "Locked Out?"
   :contact "Contact Support"
   :planstext "Exercise HIPAA rights. Match with 8 million+ U.S. providers on location, insurance, specialty. Coordinate care. Import and share care plans, images, lab results. No big-tech surveillance."
   :Monthly "Monthly"
   :Yearly "Yearly"
   :planagree "I understand that I may always export or delete Records I administer for myself and others when canceling a free or paid plan. If I do not delete Records when canceling, I understand that I may reactivate those Records with a paid plan. I understand and agree to these data retention policies and to the Terms of Service and Privacy Policy"
   :DoneButton "Done"
   :discountInfo "If you have a discount code, enter it here."
   :verificationtext "Thanks for verifying your email address!"
   :credentialstext "Use this email address to Sign In to the RK360 App. Please save all your Sign In credentials (email address, phone number, password, verbal passcode) so you can find them when your phone is not nearby."
   :Nextbutton "NEXT"
   :verifyemail "Verify Email"
   :verificationemail "Check for a “Redkangaroo Email Verification” message which we sent to this address and tap the link."
   :resendemailtext "Didn't get the email? Correct the email address below or enter another one and tap on the red “Resend Verification Email” button."
   :confirmemailbutton "CONFIRM EMAIL"
   :confusedrk360 "Go from confused to calm with the RK360"
   :reserveright "®"
   :naviapp " NAVI App"
   :removecoupon "Click here to remove coupon and see other plans."
   :policytext "I understand that I may always export or delete Records I administer for myself and others when canceling a free or paid plan. If I do not delete Records when canceling, I understand that I may reactivate those Records with a paid plan. I understand and agree to these data retention policies and to the Terms of Service and Privacy Policy"
   :entercoupontext "Please enter at least one character in the coupon code."
   :activatiofail "Activation failed. Please try again."
   :resendingotp "Resending OTP..."
   :checkboxagree "Please select the checkbox for the agreement policy"
   :failedactivationcontact "Failed to activate contact. Please try again."
   :userregistersuccess "User registered successfully! Please log in."
   :errorregistration "An unknown error occurred during registration."
   :registrationfailederror "Registration failed. Please try again."
   :signupemailphone "Email or Phone is missing"
   :retrievaltext "Unable to retrieve user ID. Please try again."
   :errorverifycode "An error occurred while verifying contact."
   :paymentprocess "Payment not processed yet"
   :subscriptionsapprove "It seems your subscription hasn't been approved yet. Please try to refresh page later. If it doesn't work - contact support."
   })

